# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bookdetails_pb2 as bookdetails__pb2


class BookDetailsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookDetails = channel.unary_unary(
                '/BookDetails/GetBookDetails',
                request_serializer=bookdetails__pb2.BookDetailsRequest.SerializeToString,
                response_deserializer=bookdetails__pb2.BookDetailsResponse.FromString,
                )
        self.GetAuthorsList = channel.unary_unary(
                '/BookDetails/GetAuthorsList',
                request_serializer=bookdetails__pb2.AuthorsListRequest.SerializeToString,
                response_deserializer=bookdetails__pb2.AuthorsListResponse.FromString,
                )


class BookDetailsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthorsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookDetailsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookDetails,
                    request_deserializer=bookdetails__pb2.BookDetailsRequest.FromString,
                    response_serializer=bookdetails__pb2.BookDetailsResponse.SerializeToString,
            ),
            'GetAuthorsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthorsList,
                    request_deserializer=bookdetails__pb2.AuthorsListRequest.FromString,
                    response_serializer=bookdetails__pb2.AuthorsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookDetails', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookDetails(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookDetails/GetBookDetails',
            bookdetails__pb2.BookDetailsRequest.SerializeToString,
            bookdetails__pb2.BookDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAuthorsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookDetails/GetAuthorsList',
            bookdetails__pb2.AuthorsListRequest.SerializeToString,
            bookdetails__pb2.AuthorsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
